GET http://localhost:5000/expenses

###
PATCH http://localhost:5000/expenses/647e348888b8ef8e3051abcb
Content-Type: application/json

{
  "name": "New I phone",
  "amount": 699,
  "currencyType": "USD"
}
###
POST http://localhost:5000/daily
Content-Type: application/json

{
  "name": "Lunch",
  "amount": 10,
  "currencyType": "USD"
}
###
DELETE http://localhost:5000/expenses/6473e296cf44d4dbb7e09ba6

