POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "James",
  "password": "abc123",
  "email": "james@gmail.com"
}
###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "Jack",
  "password": "abc123"
}
###
PATCH http://localhost:5000/expenses/647e348888b8ef8e3051abcb
Content-Type: application/json

{
  "name": "New one",
  "amount": 699,
  "currencyType": "USD"
}
###
POST http://localhost:5000/daily
Content-Type: application/json

{
  "name": "Lunch",
  "amount": 10,
  "currencyType": "USD"
}
###
DELETE http://localhost:5000/expenses/6473e296cf44d4dbb7e09ba6

